<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ucfirst($type) }} Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #000;
        }
        .info-section {
            margin-bottom: 20px;
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 5px;
        }
        .info-section p {
            margin: 5px 0;
        }
        .info-label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4a5568;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .note-section {
            margin-top: 20px;
            padding: 10px;
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $type === 'checkout' ? 'CHECKOUT' : 'CHECKIN' }} SUMMARY</h1>
        <p>{{ $date }}</p>
    </div>

    <div class="info-section">
        <p>
            <span class="info-label">{{ $type === 'checkout' ? 'Checked Out To' : 'Checked In By' }}:</span>
            @if($target)
                @if(is_object($target))
                    {{ $target->name ?? $target->display_name ?? 'N/A' }}
                @else
                    {{ $target }}
                @endif
            @else
                N/A
            @endif
        </p>
        <p>
            <span class="info-label">Administrator:</span>
            {{ $admin->first_name ?? '' }} {{ $admin->last_name ?? '' }} ({{ $admin->username ?? 'N/A' }})
        </p>
        <p>
            <span class="info-label">Total Assets:</span>
            {{ $assets->count() }}
        </p>
        <p>
            <span class="info-label">Batch ID:</span>
            {{ $batch_id }}
        </p>
    </div>

    @if($note)
    <div class="note-section">
        <strong>Note:</strong> {{ $note }}
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Asset Tag</th>
                <th>Category</th>
                <th>Model</th>
                <th>Serial</th>
                <th>Status</th>
                @if($type === 'checkout')
                <th>Location</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($assets as $index => $asset)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $asset->asset_tag ?? 'N/A' }}</td>
                <td>{{ $asset->model->category->name ?? 'N/A' }}</td>
                <td>{{ $asset->model->name ?? 'N/A' }}</td>
                <td>{{ $asset->serial ?? 'N/A' }}</td>
                <td>{{ $asset->assetstatus->name ?? 'N/A' }}</td>
                @if($type === 'checkout')
                <td>{{ $asset->location->name ?? 'N/A' }}</td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Snipe-IT Asset Management System</p>
        <p>This document is for reference purposes only</p>
    </div>
</body>
</html>
